version: "3"
services:
  docker-jupyter-zh:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8093:8888"
    volumes:
      - ./work:/work
    command: ["python","-m","jupyter","notebook","--port=8888","--allow-root","--ip=0.0.0.0","--no-browser","--NotebookApp.token='your password'"]

